//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CactusSoft.Stierlitz.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CactusSoft.Stierlitz.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT ZABBKIT.
        /// </summary>
        public static string AboutAppTitle {
            get {
                return ResourceManager.GetString("AboutAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a client-application for Zabbix monitoring system.
        ///Thanks to the app you will always be updated on your server&apos;s condition..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server....
        /// </summary>
        public static string AddServer {
            get {
                return ResourceManager.GetString("AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All events.
        /// </summary>
        public static string AllEvents {
            get {
                return ResourceManager.GetString("AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all events.
        /// </summary>
        public static string AllEventsTitle {
            get {
                return ResourceManager.GetString("AllEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved..
        /// </summary>
        public static string AllRightsReservedLabel {
            get {
                return ResourceManager.GetString("AllRightsReservedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All triggers.
        /// </summary>
        public static string AllTriggers {
            get {
                return ResourceManager.GetString("AllTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarAdd {
            get {
                return ResourceManager.GetString("AppBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        public static string AppBarData {
            get {
                return ResourceManager.GetString("AppBarData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graphs.
        /// </summary>
        public static string AppBarGraphs {
            get {
                return ResourceManager.GetString("AppBarGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string AppBarLogin {
            get {
                return ResourceManager.GetString("AppBarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string AppBarLogout {
            get {
                return ResourceManager.GetString("AppBarLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string AppBarNext {
            get {
                return ResourceManager.GetString("AppBarNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period.
        /// </summary>
        public static string AppBarPeriod {
            get {
                return ResourceManager.GetString("AppBarPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string AppBarPrevious {
            get {
                return ResourceManager.GetString("AppBarPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string AppBarPushSettings {
            get {
                return ResourceManager.GetString("AppBarPushSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefresh {
            get {
                return ResourceManager.GetString("AppBarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribe.
        /// </summary>
        public static string AppBarSubscribe {
            get {
                return ResourceManager.GetString("AppBarSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsubscribe.
        /// </summary>
        public static string AppBarUnsubscribe {
            get {
                return ResourceManager.GetString("AppBarUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZABBKIT.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ApplicationVersionLabel {
            get {
                return ResourceManager.GetString("ApplicationVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        public static string AuthorizationFailedError {
            get {
                return ResourceManager.GetString("AuthorizationFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2012, CactusSoft. All Rights Reserved..
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string CriticalErrorHasOccured {
            get {
                return ResourceManager.GetString("CriticalErrorHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        public static string DataTitle {
            get {
                return ResourceManager.GetString("DataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day events.
        /// </summary>
        public static string DayEventsTitle {
            get {
                return ResourceManager.GetString("DayEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DayFirstForm {
            get {
                return ResourceManager.GetString("DayFirstForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DaySecondForm {
            get {
                return ResourceManager.GetString("DaySecondForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DayThirdForm {
            get {
                return ResourceManager.GetString("DayThirdForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabbkit: Unhandled exception.
        /// </summary>
        public static string ErrorMailSubject {
            get {
                return ResourceManager.GetString("ErrorMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application Zabbkit has stopped unexpectedly. Send report?.
        /// </summary>
        public static string ErrorReportMessage {
            get {
                return ResourceManager.GetString("ErrorReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string EventsTitle {
            get {
                return ResourceManager.GetString("EventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        public static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host groups.
        /// </summary>
        public static string HostGroupsTitle {
            get {
                return ResourceManager.GetString("HostGroupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string HostLabel {
            get {
                return ResourceManager.GetString("HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hosts.
        /// </summary>
        public static string HostsTitle {
            get {
                return ResourceManager.GetString("HostsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string HoursFirstForm {
            get {
                return ResourceManager.GetString("HoursFirstForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string HoursSecondForm {
            get {
                return ResourceManager.GetString("HoursSecondForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string HoursThirdForm {
            get {
                return ResourceManager.GetString("HoursThirdForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtaining ID.
        /// </summary>
        public static string IdError {
            get {
                return ResourceManager.GetString("IdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified &quot;Zabbix&quot; server url is invalid.
        /// </summary>
        public static string InvalidZabbixServerUri {
            get {
                return ResourceManager.GetString("InvalidZabbixServerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MonthFirstForm {
            get {
                return ResourceManager.GetString("MonthFirstForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string MonthSecondForm {
            get {
                return ResourceManager.GetString("MonthSecondForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string MonthThirdForm {
            get {
                return ResourceManager.GetString("MonthThirdForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Internet. Please check your connection settings and try again.
        /// </summary>
        public static string NetworkConnectionProblemError {
            get {
                return ResourceManager.GetString("NetworkConnectionProblemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new server.
        /// </summary>
        public static string NewServerTitle {
            get {
                return ResourceManager.GetString("NewServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events found.
        /// </summary>
        public static string NoEventsFound {
            get {
                return ResourceManager.GetString("NoEventsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No graphs found.
        /// </summary>
        public static string NoGraphsFound {
            get {
                return ResourceManager.GetString("NoGraphsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No host groups found.
        /// </summary>
        public static string NoHostGroupsFound {
            get {
                return ResourceManager.GetString("NoHostGroupsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No servers found.
        /// </summary>
        public static string NoServersFound {
            get {
                return ResourceManager.GetString("NoServersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No triggers found.
        /// </summary>
        public static string NoTriggersFound {
            get {
                return ResourceManager.GetString("NoTriggersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabbkit application moves on another development acoout in market place. This version has already deleted from market and won&apos;t be supported in future, but the new one is available. In order to migrate to the new version, please, delete this app and download the new version from Market Place. Zabbkit continues to be free without advertizing. Sorry for inconvinience..
        /// </summary>
        public static string OldDateVersionMessage {
            get {
                return ResourceManager.GetString("OldDateVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this reminder again.
        /// </summary>
        public static string PleaseRateApplicationDoNotShowAgainText {
            get {
                return ResourceManager.GetString("PleaseRateApplicationDoNotShowAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope you are enjoying using the application!
        ///
        ///We will be glad to hear your feedback..
        /// </summary>
        public static string PleaseRateApplicationMessage {
            get {
                return ResourceManager.GetString("PleaseRateApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to rate the application in Marketplace?.
        /// </summary>
        public static string PleaseRateApplicationMessageTitle {
            get {
                return ResourceManager.GetString("PleaseRateApplicationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string PoweredByLabel {
            get {
                return ResourceManager.GetString("PoweredByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to push settings.
        /// </summary>
        public static string PushSettingsTitle {
            get {
                return ResourceManager.GetString("PushSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your id:.
        /// </summary>
        public static string PushToken {
            get {
                return ResourceManager.GetString("PushToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server already exist.
        /// </summary>
        public static string ServerAlreadyExist {
            get {
                return ResourceManager.GetString("ServerAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication error.
        /// </summary>
        public static string ServerCommunicationErrorHasOccured {
            get {
                return ResourceManager.GetString("ServerCommunicationErrorHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerLabel {
            get {
                return ResourceManager.GetString("ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servers.
        /// </summary>
        public static string ServersTitle {
            get {
                return ResourceManager.GetString("ServersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string ShortDay {
            get {
                return ResourceManager.GetString("ShortDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string ShortHour {
            get {
                return ResourceManager.GetString("ShortHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string ShortMinute {
            get {
                return ResourceManager.GetString("ShortMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string ShortSecond {
            get {
                return ResourceManager.GetString("ShortSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string SupportLinkLabel {
            get {
                return ResourceManager.GetString("SupportLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabbkit: Support.
        /// </summary>
        public static string SupportMailSubject {
            get {
                return ResourceManager.GetString("SupportMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeline.
        /// </summary>
        public static string TimelineTitle {
            get {
                return ResourceManager.GetString("TimelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string TriggerLabel {
            get {
                return ResourceManager.GetString("TriggerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        public static string TriggersTitle {
            get {
                return ResourceManager.GetString("TriggersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user agreement.
        /// </summary>
        public static string UserAgreementTitle {
            get {
                return ResourceManager.GetString("UserAgreementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web.
        /// </summary>
        public static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabbkit notification ID.
        /// </summary>
        public static string WPDeviceToken {
            get {
                return ResourceManager.GetString("WPDeviceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s possible to receive push notifications about server events on your smartphone. 
        ///Detailed instructions are available on Zabbix comunity forum:.
        /// </summary>
        public static string ZabbixLinkText {
            get {
                return ResourceManager.GetString("ZabbixLinkText", resourceCulture);
            }
        }
    }
}
